version: '2'
services:
  nginx:
    image: mritd/nginx
    container_name: nginx
    restart: always
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx/:/var/log/nginx/
      - ./vippasswd:/etc/nginx/conf/vippasswd
    volumes_from:
      - piwik_app
    links:
      - jekyll
      - videovip
      - idea
      - yum
      - piwik_app
      - radicale
    ports:
      - "80:80"
      - "443:443"
  jekyll:
    image: mritd/jekyll
    container_name: jekyll
    restart: always
  videovip:
    image: mritd/videovip
    container_name: vip
    restart: always
  idea:
    image: mritd/idea
    container_name: idea
    restart: always
  yum:
    image: mritd/yum
    container_name: yum
    restart: always  
  piwik_db:
    image: mysql:5.7.17
    container_name: piwik_mysql
    restart: always
    volumes:
      - /data/piwik/mysql/runtime:/var/lib/mysql
  piwik_app:
    image: mritd/piwik:3.3.0
    container_name: piwik
    restart: always
    links:
      - piwik_db
    volumes:
      - /data/piwik/config:/var/www/html/config
  radicale:
    image: mritd/radicale:2.1.5
    container_name: 2do
    restart: always
    volumes:
      - /data/radicale:/data/radicale
  idgen:
    image: mritd/idgen:v0.0.3
    container_name: idgen
    restart: always
